/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "./common";

export interface SubscriptionVaultInterface extends utils.Interface {
  functions: {
    "billingDay()": FunctionFragment;
    "cUSD()": FunctionFragment;
    "confirmPaymentAndReset()": FunctionFragment;
    "creator()": FunctionFragment;
    "cycleActive()": FunctionFragment;
    "cycleDeadline()": FunctionFragment;
    "executePayment()": FunctionFragment;
    "factory()": FunctionFragment;
    "fundShare()": FunctionFragment;
    "getCycleDeadline()": FunctionFragment;
    "getFundingStatus()": FunctionFragment;
    "getMember(address)": FunctionFragment;
    "getMembers()": FunctionFragment;
    "initialize(address,uint256,uint256,address,address[],uint256[],address,address,address)": FunctionFragment;
    "isMember(address)": FunctionFragment;
    "keeper()": FunctionFragment;
    "memberList(uint256)": FunctionFragment;
    "members(address)": FunctionFragment;
    "merchantAddress()": FunctionFragment;
    "monthlyAmount()": FunctionFragment;
    "refundCycle()": FunctionFragment;
    "relayer()": FunctionFragment;
    "totalFunded()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "billingDay"
      | "cUSD"
      | "confirmPaymentAndReset"
      | "creator"
      | "cycleActive"
      | "cycleDeadline"
      | "executePayment"
      | "factory"
      | "fundShare"
      | "getCycleDeadline"
      | "getFundingStatus"
      | "getMember"
      | "getMembers"
      | "initialize"
      | "isMember"
      | "keeper"
      | "memberList"
      | "members"
      | "merchantAddress"
      | "monthlyAmount"
      | "refundCycle"
      | "relayer"
      | "totalFunded"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "billingDay",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "cUSD", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "confirmPaymentAndReset",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "creator", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "cycleActive",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "cycleDeadline",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "executePayment",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "factory", values?: undefined): string;
  encodeFunctionData(functionFragment: "fundShare", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getCycleDeadline",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getFundingStatus",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getMember",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "getMembers",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<string>[],
      PromiseOrValue<BigNumberish>[],
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "isMember",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(functionFragment: "keeper", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "memberList",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "members",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "merchantAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "monthlyAmount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "refundCycle",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "relayer", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "totalFunded",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "billingDay", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "cUSD", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "confirmPaymentAndReset",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "creator", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "cycleActive",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cycleDeadline",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executePayment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "factory", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "fundShare", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getCycleDeadline",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getFundingStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getMember", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getMembers", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isMember", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "keeper", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "memberList", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "members", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "merchantAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "monthlyAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "refundCycle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "relayer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalFunded",
    data: BytesLike
  ): Result;

  events: {
    "CycleRefunded(uint256)": EventFragment;
    "CycleReset(uint256)": EventFragment;
    "MemberFunded(address,uint256,uint256)": EventFragment;
    "PaymentExecuted(uint256,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "CycleRefunded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "CycleReset"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "MemberFunded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "PaymentExecuted"): EventFragment;
}

export interface CycleRefundedEventObject {
  timestamp: BigNumber;
}
export type CycleRefundedEvent = TypedEvent<
  [BigNumber],
  CycleRefundedEventObject
>;

export type CycleRefundedEventFilter = TypedEventFilter<CycleRefundedEvent>;

export interface CycleResetEventObject {
  nextDeadline: BigNumber;
}
export type CycleResetEvent = TypedEvent<[BigNumber], CycleResetEventObject>;

export type CycleResetEventFilter = TypedEventFilter<CycleResetEvent>;

export interface MemberFundedEventObject {
  member: string;
  amount: BigNumber;
  timestamp: BigNumber;
}
export type MemberFundedEvent = TypedEvent<
  [string, BigNumber, BigNumber],
  MemberFundedEventObject
>;

export type MemberFundedEventFilter = TypedEventFilter<MemberFundedEvent>;

export interface PaymentExecutedEventObject {
  amount: BigNumber;
  timestamp: BigNumber;
}
export type PaymentExecutedEvent = TypedEvent<
  [BigNumber, BigNumber],
  PaymentExecutedEventObject
>;

export type PaymentExecutedEventFilter = TypedEventFilter<PaymentExecutedEvent>;

export interface SubscriptionVault extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: SubscriptionVaultInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    billingDay(overrides?: CallOverrides): Promise<[BigNumber]>;

    cUSD(overrides?: CallOverrides): Promise<[string]>;

    confirmPaymentAndReset(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    creator(overrides?: CallOverrides): Promise<[string]>;

    cycleActive(overrides?: CallOverrides): Promise<[boolean]>;

    cycleDeadline(overrides?: CallOverrides): Promise<[BigNumber]>;

    executePayment(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    factory(overrides?: CallOverrides): Promise<[string]>;

    fundShare(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    getCycleDeadline(overrides?: CallOverrides): Promise<[BigNumber]>;

    getFundingStatus(
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber, BigNumber] & {
        totalFundedAmount: BigNumber;
        totalRequired: BigNumber;
        membersCount: BigNumber;
        membersFunded: BigNumber;
      }
    >;

    getMember(
      addr: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [string, BigNumber, BigNumber, boolean] & {
        wallet: string;
        sharePercent: BigNumber;
        shareAmount: BigNumber;
        funded: boolean;
      }
    >;

    getMembers(overrides?: CallOverrides): Promise<[string[]]>;

    initialize(
      _cUSD: PromiseOrValue<string>,
      _monthlyAmount: PromiseOrValue<BigNumberish>,
      _billingDay: PromiseOrValue<BigNumberish>,
      _merchantAddress: PromiseOrValue<string>,
      _memberAddresses: PromiseOrValue<string>[],
      _memberShares: PromiseOrValue<BigNumberish>[],
      _keeper: PromiseOrValue<string>,
      _relayer: PromiseOrValue<string>,
      _creator: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    isMember(
      addr: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    keeper(overrides?: CallOverrides): Promise<[string]>;

    memberList(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    members(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [string, BigNumber, BigNumber, boolean] & {
        wallet: string;
        sharePercent: BigNumber;
        shareAmount: BigNumber;
        funded: boolean;
      }
    >;

    merchantAddress(overrides?: CallOverrides): Promise<[string]>;

    monthlyAmount(overrides?: CallOverrides): Promise<[BigNumber]>;

    refundCycle(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    relayer(overrides?: CallOverrides): Promise<[string]>;

    totalFunded(overrides?: CallOverrides): Promise<[BigNumber]>;
  };

  billingDay(overrides?: CallOverrides): Promise<BigNumber>;

  cUSD(overrides?: CallOverrides): Promise<string>;

  confirmPaymentAndReset(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  creator(overrides?: CallOverrides): Promise<string>;

  cycleActive(overrides?: CallOverrides): Promise<boolean>;

  cycleDeadline(overrides?: CallOverrides): Promise<BigNumber>;

  executePayment(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  factory(overrides?: CallOverrides): Promise<string>;

  fundShare(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  getCycleDeadline(overrides?: CallOverrides): Promise<BigNumber>;

  getFundingStatus(
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber, BigNumber, BigNumber] & {
      totalFundedAmount: BigNumber;
      totalRequired: BigNumber;
      membersCount: BigNumber;
      membersFunded: BigNumber;
    }
  >;

  getMember(
    addr: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<
    [string, BigNumber, BigNumber, boolean] & {
      wallet: string;
      sharePercent: BigNumber;
      shareAmount: BigNumber;
      funded: boolean;
    }
  >;

  getMembers(overrides?: CallOverrides): Promise<string[]>;

  initialize(
    _cUSD: PromiseOrValue<string>,
    _monthlyAmount: PromiseOrValue<BigNumberish>,
    _billingDay: PromiseOrValue<BigNumberish>,
    _merchantAddress: PromiseOrValue<string>,
    _memberAddresses: PromiseOrValue<string>[],
    _memberShares: PromiseOrValue<BigNumberish>[],
    _keeper: PromiseOrValue<string>,
    _relayer: PromiseOrValue<string>,
    _creator: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  isMember(
    addr: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  keeper(overrides?: CallOverrides): Promise<string>;

  memberList(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  members(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<
    [string, BigNumber, BigNumber, boolean] & {
      wallet: string;
      sharePercent: BigNumber;
      shareAmount: BigNumber;
      funded: boolean;
    }
  >;

  merchantAddress(overrides?: CallOverrides): Promise<string>;

  monthlyAmount(overrides?: CallOverrides): Promise<BigNumber>;

  refundCycle(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  relayer(overrides?: CallOverrides): Promise<string>;

  totalFunded(overrides?: CallOverrides): Promise<BigNumber>;

  callStatic: {
    billingDay(overrides?: CallOverrides): Promise<BigNumber>;

    cUSD(overrides?: CallOverrides): Promise<string>;

    confirmPaymentAndReset(overrides?: CallOverrides): Promise<void>;

    creator(overrides?: CallOverrides): Promise<string>;

    cycleActive(overrides?: CallOverrides): Promise<boolean>;

    cycleDeadline(overrides?: CallOverrides): Promise<BigNumber>;

    executePayment(overrides?: CallOverrides): Promise<void>;

    factory(overrides?: CallOverrides): Promise<string>;

    fundShare(overrides?: CallOverrides): Promise<void>;

    getCycleDeadline(overrides?: CallOverrides): Promise<BigNumber>;

    getFundingStatus(
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber, BigNumber] & {
        totalFundedAmount: BigNumber;
        totalRequired: BigNumber;
        membersCount: BigNumber;
        membersFunded: BigNumber;
      }
    >;

    getMember(
      addr: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [string, BigNumber, BigNumber, boolean] & {
        wallet: string;
        sharePercent: BigNumber;
        shareAmount: BigNumber;
        funded: boolean;
      }
    >;

    getMembers(overrides?: CallOverrides): Promise<string[]>;

    initialize(
      _cUSD: PromiseOrValue<string>,
      _monthlyAmount: PromiseOrValue<BigNumberish>,
      _billingDay: PromiseOrValue<BigNumberish>,
      _merchantAddress: PromiseOrValue<string>,
      _memberAddresses: PromiseOrValue<string>[],
      _memberShares: PromiseOrValue<BigNumberish>[],
      _keeper: PromiseOrValue<string>,
      _relayer: PromiseOrValue<string>,
      _creator: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    isMember(
      addr: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    keeper(overrides?: CallOverrides): Promise<string>;

    memberList(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    members(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [string, BigNumber, BigNumber, boolean] & {
        wallet: string;
        sharePercent: BigNumber;
        shareAmount: BigNumber;
        funded: boolean;
      }
    >;

    merchantAddress(overrides?: CallOverrides): Promise<string>;

    monthlyAmount(overrides?: CallOverrides): Promise<BigNumber>;

    refundCycle(overrides?: CallOverrides): Promise<void>;

    relayer(overrides?: CallOverrides): Promise<string>;

    totalFunded(overrides?: CallOverrides): Promise<BigNumber>;
  };

  filters: {
    "CycleRefunded(uint256)"(timestamp?: null): CycleRefundedEventFilter;
    CycleRefunded(timestamp?: null): CycleRefundedEventFilter;

    "CycleReset(uint256)"(nextDeadline?: null): CycleResetEventFilter;
    CycleReset(nextDeadline?: null): CycleResetEventFilter;

    "MemberFunded(address,uint256,uint256)"(
      member?: PromiseOrValue<string> | null,
      amount?: null,
      timestamp?: null
    ): MemberFundedEventFilter;
    MemberFunded(
      member?: PromiseOrValue<string> | null,
      amount?: null,
      timestamp?: null
    ): MemberFundedEventFilter;

    "PaymentExecuted(uint256,uint256)"(
      amount?: null,
      timestamp?: null
    ): PaymentExecutedEventFilter;
    PaymentExecuted(
      amount?: null,
      timestamp?: null
    ): PaymentExecutedEventFilter;
  };

  estimateGas: {
    billingDay(overrides?: CallOverrides): Promise<BigNumber>;

    cUSD(overrides?: CallOverrides): Promise<BigNumber>;

    confirmPaymentAndReset(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    creator(overrides?: CallOverrides): Promise<BigNumber>;

    cycleActive(overrides?: CallOverrides): Promise<BigNumber>;

    cycleDeadline(overrides?: CallOverrides): Promise<BigNumber>;

    executePayment(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    factory(overrides?: CallOverrides): Promise<BigNumber>;

    fundShare(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    getCycleDeadline(overrides?: CallOverrides): Promise<BigNumber>;

    getFundingStatus(overrides?: CallOverrides): Promise<BigNumber>;

    getMember(
      addr: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getMembers(overrides?: CallOverrides): Promise<BigNumber>;

    initialize(
      _cUSD: PromiseOrValue<string>,
      _monthlyAmount: PromiseOrValue<BigNumberish>,
      _billingDay: PromiseOrValue<BigNumberish>,
      _merchantAddress: PromiseOrValue<string>,
      _memberAddresses: PromiseOrValue<string>[],
      _memberShares: PromiseOrValue<BigNumberish>[],
      _keeper: PromiseOrValue<string>,
      _relayer: PromiseOrValue<string>,
      _creator: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    isMember(
      addr: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    keeper(overrides?: CallOverrides): Promise<BigNumber>;

    memberList(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    members(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    merchantAddress(overrides?: CallOverrides): Promise<BigNumber>;

    monthlyAmount(overrides?: CallOverrides): Promise<BigNumber>;

    refundCycle(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    relayer(overrides?: CallOverrides): Promise<BigNumber>;

    totalFunded(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    billingDay(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    cUSD(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    confirmPaymentAndReset(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    creator(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    cycleActive(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    cycleDeadline(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    executePayment(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    factory(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    fundShare(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    getCycleDeadline(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getFundingStatus(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getMember(
      addr: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getMembers(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    initialize(
      _cUSD: PromiseOrValue<string>,
      _monthlyAmount: PromiseOrValue<BigNumberish>,
      _billingDay: PromiseOrValue<BigNumberish>,
      _merchantAddress: PromiseOrValue<string>,
      _memberAddresses: PromiseOrValue<string>[],
      _memberShares: PromiseOrValue<BigNumberish>[],
      _keeper: PromiseOrValue<string>,
      _relayer: PromiseOrValue<string>,
      _creator: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    isMember(
      addr: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    keeper(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    memberList(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    members(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    merchantAddress(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    monthlyAmount(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    refundCycle(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    relayer(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    totalFunded(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
