/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "./common";

export interface VaultFactoryInterface extends utils.Interface {
  functions: {
    "cUSD()": FunctionFragment;
    "createVault(uint256,uint256,address,address[],uint256[],string)": FunctionFragment;
    "creatorVaults(address,uint256)": FunctionFragment;
    "getCreatorVaults(address)": FunctionFragment;
    "getCreatorVaultsCount(address)": FunctionFragment;
    "getVaultAt(uint256)": FunctionFragment;
    "getVaultsCount()": FunctionFragment;
    "isVault(address)": FunctionFragment;
    "isVaultAddress(address)": FunctionFragment;
    "keeper()": FunctionFragment;
    "owner()": FunctionFragment;
    "relayer()": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "setCUSD(address)": FunctionFragment;
    "setKeeper(address)": FunctionFragment;
    "setRelayer(address)": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "vaults(uint256)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "cUSD"
      | "createVault"
      | "creatorVaults"
      | "getCreatorVaults"
      | "getCreatorVaultsCount"
      | "getVaultAt"
      | "getVaultsCount"
      | "isVault"
      | "isVaultAddress"
      | "keeper"
      | "owner"
      | "relayer"
      | "renounceOwnership"
      | "setCUSD"
      | "setKeeper"
      | "setRelayer"
      | "transferOwnership"
      | "vaults"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "cUSD", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "createVault",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<string>[],
      PromiseOrValue<BigNumberish>[],
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "creatorVaults",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getCreatorVaults",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "getCreatorVaultsCount",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "getVaultAt",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getVaultsCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isVault",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "isVaultAddress",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(functionFragment: "keeper", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "relayer", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setCUSD",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "setKeeper",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "setRelayer",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "vaults",
    values: [PromiseOrValue<BigNumberish>]
  ): string;

  decodeFunctionResult(functionFragment: "cUSD", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createVault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "creatorVaults",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCreatorVaults",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCreatorVaultsCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getVaultAt", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getVaultsCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isVault", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isVaultAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "keeper", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "relayer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setCUSD", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setKeeper", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setRelayer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "vaults", data: BytesLike): Result;

  events: {
    "CUSDUpdated(address)": EventFragment;
    "KeeperUpdated(address)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
    "RelayerUpdated(address)": EventFragment;
    "VaultCreated(address,address,string)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "CUSDUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "KeeperUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RelayerUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "VaultCreated"): EventFragment;
}

export interface CUSDUpdatedEventObject {
  newCUSD: string;
}
export type CUSDUpdatedEvent = TypedEvent<[string], CUSDUpdatedEventObject>;

export type CUSDUpdatedEventFilter = TypedEventFilter<CUSDUpdatedEvent>;

export interface KeeperUpdatedEventObject {
  newKeeper: string;
}
export type KeeperUpdatedEvent = TypedEvent<[string], KeeperUpdatedEventObject>;

export type KeeperUpdatedEventFilter = TypedEventFilter<KeeperUpdatedEvent>;

export interface OwnershipTransferredEventObject {
  previousOwner: string;
  newOwner: string;
}
export type OwnershipTransferredEvent = TypedEvent<
  [string, string],
  OwnershipTransferredEventObject
>;

export type OwnershipTransferredEventFilter =
  TypedEventFilter<OwnershipTransferredEvent>;

export interface RelayerUpdatedEventObject {
  newRelayer: string;
}
export type RelayerUpdatedEvent = TypedEvent<
  [string],
  RelayerUpdatedEventObject
>;

export type RelayerUpdatedEventFilter = TypedEventFilter<RelayerUpdatedEvent>;

export interface VaultCreatedEventObject {
  vault: string;
  creator: string;
  serviceName: string;
}
export type VaultCreatedEvent = TypedEvent<
  [string, string, string],
  VaultCreatedEventObject
>;

export type VaultCreatedEventFilter = TypedEventFilter<VaultCreatedEvent>;

export interface VaultFactory extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: VaultFactoryInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    cUSD(overrides?: CallOverrides): Promise<[string]>;

    createVault(
      monthlyAmount: PromiseOrValue<BigNumberish>,
      billingDay: PromiseOrValue<BigNumberish>,
      merchantAddress: PromiseOrValue<string>,
      members: PromiseOrValue<string>[],
      memberShares: PromiseOrValue<BigNumberish>[],
      serviceName: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    creatorVaults(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getCreatorVaults(
      creator: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[string[]]>;

    getCreatorVaultsCount(
      creator: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getVaultAt(
      index: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getVaultsCount(overrides?: CallOverrides): Promise<[BigNumber]>;

    isVault(
      addr: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    isVaultAddress(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    keeper(overrides?: CallOverrides): Promise<[string]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    relayer(overrides?: CallOverrides): Promise<[string]>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setCUSD(
      _cUSD: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setKeeper(
      _keeper: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setRelayer(
      _relayer: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    vaults(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>;
  };

  cUSD(overrides?: CallOverrides): Promise<string>;

  createVault(
    monthlyAmount: PromiseOrValue<BigNumberish>,
    billingDay: PromiseOrValue<BigNumberish>,
    merchantAddress: PromiseOrValue<string>,
    members: PromiseOrValue<string>[],
    memberShares: PromiseOrValue<BigNumberish>[],
    serviceName: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  creatorVaults(
    arg0: PromiseOrValue<string>,
    arg1: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  getCreatorVaults(
    creator: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<string[]>;

  getCreatorVaultsCount(
    creator: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getVaultAt(
    index: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  getVaultsCount(overrides?: CallOverrides): Promise<BigNumber>;

  isVault(
    addr: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  isVaultAddress(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  keeper(overrides?: CallOverrides): Promise<string>;

  owner(overrides?: CallOverrides): Promise<string>;

  relayer(overrides?: CallOverrides): Promise<string>;

  renounceOwnership(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setCUSD(
    _cUSD: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setKeeper(
    _keeper: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setRelayer(
    _relayer: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  transferOwnership(
    newOwner: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  vaults(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  callStatic: {
    cUSD(overrides?: CallOverrides): Promise<string>;

    createVault(
      monthlyAmount: PromiseOrValue<BigNumberish>,
      billingDay: PromiseOrValue<BigNumberish>,
      merchantAddress: PromiseOrValue<string>,
      members: PromiseOrValue<string>[],
      memberShares: PromiseOrValue<BigNumberish>[],
      serviceName: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<string>;

    creatorVaults(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    getCreatorVaults(
      creator: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<string[]>;

    getCreatorVaultsCount(
      creator: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getVaultAt(
      index: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    getVaultsCount(overrides?: CallOverrides): Promise<BigNumber>;

    isVault(
      addr: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    isVaultAddress(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    keeper(overrides?: CallOverrides): Promise<string>;

    owner(overrides?: CallOverrides): Promise<string>;

    relayer(overrides?: CallOverrides): Promise<string>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    setCUSD(
      _cUSD: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    setKeeper(
      _keeper: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    setRelayer(
      _relayer: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    vaults(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {
    "CUSDUpdated(address)"(
      newCUSD?: PromiseOrValue<string> | null
    ): CUSDUpdatedEventFilter;
    CUSDUpdated(
      newCUSD?: PromiseOrValue<string> | null
    ): CUSDUpdatedEventFilter;

    "KeeperUpdated(address)"(
      newKeeper?: PromiseOrValue<string> | null
    ): KeeperUpdatedEventFilter;
    KeeperUpdated(
      newKeeper?: PromiseOrValue<string> | null
    ): KeeperUpdatedEventFilter;

    "OwnershipTransferred(address,address)"(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;
    OwnershipTransferred(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;

    "RelayerUpdated(address)"(
      newRelayer?: PromiseOrValue<string> | null
    ): RelayerUpdatedEventFilter;
    RelayerUpdated(
      newRelayer?: PromiseOrValue<string> | null
    ): RelayerUpdatedEventFilter;

    "VaultCreated(address,address,string)"(
      vault?: PromiseOrValue<string> | null,
      creator?: PromiseOrValue<string> | null,
      serviceName?: null
    ): VaultCreatedEventFilter;
    VaultCreated(
      vault?: PromiseOrValue<string> | null,
      creator?: PromiseOrValue<string> | null,
      serviceName?: null
    ): VaultCreatedEventFilter;
  };

  estimateGas: {
    cUSD(overrides?: CallOverrides): Promise<BigNumber>;

    createVault(
      monthlyAmount: PromiseOrValue<BigNumberish>,
      billingDay: PromiseOrValue<BigNumberish>,
      merchantAddress: PromiseOrValue<string>,
      members: PromiseOrValue<string>[],
      memberShares: PromiseOrValue<BigNumberish>[],
      serviceName: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    creatorVaults(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getCreatorVaults(
      creator: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getCreatorVaultsCount(
      creator: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getVaultAt(
      index: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getVaultsCount(overrides?: CallOverrides): Promise<BigNumber>;

    isVault(
      addr: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isVaultAddress(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    keeper(overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    relayer(overrides?: CallOverrides): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setCUSD(
      _cUSD: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setKeeper(
      _keeper: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setRelayer(
      _relayer: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    vaults(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    cUSD(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    createVault(
      monthlyAmount: PromiseOrValue<BigNumberish>,
      billingDay: PromiseOrValue<BigNumberish>,
      merchantAddress: PromiseOrValue<string>,
      members: PromiseOrValue<string>[],
      memberShares: PromiseOrValue<BigNumberish>[],
      serviceName: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    creatorVaults(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getCreatorVaults(
      creator: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getCreatorVaultsCount(
      creator: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getVaultAt(
      index: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getVaultsCount(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    isVault(
      addr: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isVaultAddress(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    keeper(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    relayer(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setCUSD(
      _cUSD: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setKeeper(
      _keeper: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setRelayer(
      _relayer: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    vaults(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
